-- MySQL Script generated by MySQL Workbench
-- Mon Sep 21 17:23:16 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0;
SET @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE =
        'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bullfinch
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bullfinch
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bullfinch` DEFAULT CHARACTER SET utf8;
USE `bullfinch`;

-- -----------------------------------------------------
-- Table `bullfinch`.`wallet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bullfinch`.`wallet`
(
    `wallet_id` BIGINT  NOT NULL AUTO_INCREMENT,
    `balance`   DECIMAL NOT NULL,
    PRIMARY KEY (`wallet_id`)
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bullfinch`.`rating`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bullfinch`.`rating`
(
    `rating_id`   BIGINT      NOT NULL AUTO_INCREMENT,
    `rating_name` VARCHAR(20) NOT NULL,
    PRIMARY KEY (`rating_id`)
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bullfinch`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bullfinch`.`role`
(
    `role_id`   BIGINT      NOT NULL AUTO_INCREMENT,
    `role_name` VARCHAR(20) NOT NULL,
    PRIMARY KEY (`role_id`)
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bullfinch`.`user_account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bullfinch`.`user_account`
(
    `user_account_id` BIGINT      NOT NULL AUTO_INCREMENT,
    `email`           VARCHAR(55) NULL,
    `login`           VARCHAR(20) NOT NULL,
    `password`        VARCHAR(40) NOT NULL,
    `first_name`      VARCHAR(25) NULL,
    `second_name`     VARCHAR(25) NULL,
    `phone_number`    VARCHAR(13) NULL,
    `is_blocked`      TINYINT     NULL,
    `is_activated`    TINYINT     NULL,
    `role_id_fk`      BIGINT      NOT NULL,
    `wallet_id_fk`    BIGINT      NULL,
    `rating_id_fk`    BIGINT      NULL,
    PRIMARY KEY (`user_account_id`),
    UNIQUE INDEX `login_UNIQUE` (`email` ASC) VISIBLE,
    INDEX `fk_user_account_wallet1_idx` (`wallet_id_fk` ASC) VISIBLE,
    INDEX `fk_user_account_rating1_idx` (`rating_id_fk` ASC) VISIBLE,
    UNIQUE INDEX `user_account_login_UNIQUE` (`login` ASC) VISIBLE,
    INDEX `fk_user_account_role1_idx` (`role_id_fk` ASC) VISIBLE,
    CONSTRAINT `fk_user_account_wallet1`
        FOREIGN KEY (`wallet_id_fk`)
            REFERENCES `bullfinch`.`wallet` (`wallet_id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_user_account_rating1`
        FOREIGN KEY (`rating_id_fk`)
            REFERENCES `bullfinch`.`rating` (`rating_id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_user_account_role1`
        FOREIGN KEY (`role_id_fk`)
            REFERENCES `bullfinch`.`role` (`role_id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bullfinch`.`image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bullfinch`.`image`
(
    `image_id`   BIGINT      NOT NULL AUTO_INCREMENT,
    `image_name` VARCHAR(36) NOT NULL,
    PRIMARY KEY (`image_id`)
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bullfinch`.`tattoo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bullfinch`.`tattoo`
(
    `tattoo_id`          BIGINT       NOT NULL AUTO_INCREMENT,
    `tattoo_name`        VARCHAR(25)  NOT NULL,
    `tattoo_description` VARCHAR(256) NOT NULL,
    `tattoo_price`       DECIMAL      NOT NULL,
    `tattoo_rating`      TINYINT      NOT NULL,
    `is_allowed`         TINYINT      NOT NULL,
    `is_archived`        TINYINT      NOT NULL,
    `image_id`           BIGINT       NOT NULL,
    PRIMARY KEY (`tattoo_id`),
    INDEX `fk_tattoo_image1_idx` (`image_id` ASC) VISIBLE,
    CONSTRAINT `fk_tattoo_image1`
        FOREIGN KEY (`image_id`)
            REFERENCES `bullfinch`.`image` (`image_id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bullfinch`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bullfinch`.`order`
(
    `order_id`           BIGINT       NOT NULL AUTO_INCREMENT,
    `order_price`        DECIMAL      NOT NULL,
    `date`               BIGINT       NOT NULL,
    `order_description`  VARCHAR(256) NOT NULL,
    `user_account_id_fk` BIGINT       NOT NULL,
    `tattoo_id_fk`       BIGINT       NOT NULL,
    PRIMARY KEY (`order_id`),
    INDEX `fk_order_user_account1_idx` (`user_account_id_fk` ASC) VISIBLE,
    INDEX `fk_order_tatoo1_idx` (`tattoo_id_fk` ASC) VISIBLE,
    CONSTRAINT `fk_order_user_account1`
        FOREIGN KEY (`user_account_id_fk`)
            REFERENCES `bullfinch`.`user_account` (`user_account_id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_order_tatoo1`
        FOREIGN KEY (`tattoo_id_fk`)
            REFERENCES `bullfinch`.`tattoo` (`tattoo_id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bullfinch`.`discount`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bullfinch`.`discount`
(
    `discount_id`        BIGINT  NOT NULL AUTO_INCREMENT,
    `discount_percent`   TINYINT NOT NULL,
    `end_date`           BIGINT  NOT NULL,
    `user_account_id_fk` BIGINT  NOT NULL,
    PRIMARY KEY (`discount_id`),
    INDEX `fk_discount_user_account1_idx` (`user_account_id_fk` ASC) VISIBLE,
    CONSTRAINT `fk_discount_user_account1`
        FOREIGN KEY (`user_account_id_fk`)
            REFERENCES `bullfinch`.`user_account` (`user_account_id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;
